<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../common.props" Condition="Exists('../common.props')" />

	<PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>form_test</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
