<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../common.props" Condition="Exists('../common.props')" />

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>form_test</RootNamespace>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<OutputType>WinExe</OutputType>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="TencentCloudSDK.Dnspod" Version="3.0.1239" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ApiClients\ApiClients.csproj" />
	</ItemGroup>

</Project>
